let productList = [
  {
    title: 'Spices',
    image: '/images/products/Spices.jpg',
    imageAltText: 'Image of spices on a table.',
    note: 'All Varieties, raw and powdered.',
    description: [
      'Pepper',
      'Chilli',
      'Salt',
      'Turmeric',
      'Cinnamon',
      'Cardamom',
      'Other spices',
    ],
  },
  {
    title: 'Cereals',
    image: '/images/products/Cereals.jpg',
    imageAltText: 'Cereals.',
    note: 'All Varieties, raw and powdered.',
    description: ['Rice', 'Wheat', 'Others'],
  },
  {
    title: 'Vegetables & Fruits',
    image: '/images/products/VegetablesAndFruits.jpg',
    imageAltText: 'Vegetables and fruits.',
    note: 'All Varieties, raw and powdered.',
    description: [
      'Tomato',
      'Potato',
      'Carrot',
      'Onion',
      'Beans',
      'drumstick',
      'Other vegetables and fruits',
    ],
  },
  {
    title: 'Textiles',
    image: '/images/products/TextilesOnTable.jpg',
    imageAltText: 'Textiles.',
    note: 'All Varieties.',
    description: [
      'Shirts and T-shirts',
      'Coats and leather jackets',
      'Silk, cotton and jute materials',
      'Sarees, Salwar and night dress',
      'Swimsuits',
      'Carpets, curtains and table cloths',
      'Pants, shorts, jeans, underpants',
    ],
  },
  {
    title: 'Handcrafts',
    image: '/images/products/HandCraftRoom.jpg',
    imageAltText: 'Handcraft items.',
    note: 'All Varieties.',
    description: [
      'Baskets',
      'Eco friendly plates',
      'Hand fans',
      'Straw and bamboo curtains',
      'Potteries',
      'Utensils and containers',
      'Ornaments',
    ],
  },
]

export default productList
